version: '3.8'

services:
  date-website:
    image: $DOCKERHUB_USERNAME/date-website:latest  # Replace with your Docker Hub image name
    container_name: date-website
    ports:
      - "8081:80"

  lorem-website:
    image: $DOCKERHUB_USERNAME/lorem-website:latest  # Replace with your Docker Hub image name
    container_name: lorem-website
    ports:
      - "8082:80"

  routing-service:
    image: $DOCKERHUB_USERNAME/routing-service:latest  # Replace with your Docker Hub image name
    container_name: routing-service
    ports:
      - "8080:80"
    depends_on:
      - date-website
      - lorem-website