version: '3.8'

services:
  date-website:
    image: ssubhash001/date-website:main-d0cd9f # Replace with your Docker Hub image name
    container_name: date-website
    ports:
      - "8081:80"
    networks:
      - app-network

  lorem-website:
    image: ssubhash001/lorem-website:main-d0cd9f  # Replace with your Docker Hub image name
    container_name: lorem-website
    ports:
      - "8082:80"
    networks:
      - app-network

  routing-service:
    image: ssubhash001/routing-service:main-d0cd9f # Replace with your Docker Hub image name
    container_name: routing-service
    ports:
      - "8080:80"
    depends_on:
      - date-website
      - lorem-website
    networks:
      - app-network

networks:
  app-network:
    driver: bridge