name: Docker Build and Push

on:
  push:
    paths:
      - 'date-website/**'
      - 'lorem-website/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download Alpine minirootfs
        run: |
          mkdir -p minrootfs
          wget https://dl-cdn.alpinelinux.org/alpine/v3.21/releases/aarch64/alpine-minirootfs-3.21.3-aarch64.tar.gz -O minrootfs/alpine-minirootfs.tar.gz
          tar -xzf minrootfs/alpine-minirootfs.tar.gz -C minrootfs

      - name: Build and Push Date Website
        run: |
          cd date-website
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/date-website:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/date-website:latest

      - name: Build and Push Lorem Website
        run: |
          cd lorem-website
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lorem-website:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/lorem-website:latest