name: Docker Build and Push

on:
  push:
    paths:
      - 'date-website/**'
      - 'lorem-website/**'
      - 'routing-service/**'
  workflow_dispatch:  # Allow manual triggering via GitHub UI

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract branch name and commit hash
        id: extract
        run: |
          BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          COMMIT_HASH=$(echo ${{ github.sha }} | cut -c1-6)
          echo "Branch Name: $BRANCH_NAME"
          echo "Commit Hash: $COMMIT_HASH"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV

      - name: Build and Push Date Website
        # if: contains(github.event.head_commit.modified, 'date-website/') || github.event_name == 'workflow_dispatch'
        run: |
          cd date-website
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/date-website:${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/date-website:${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }}

      - name: Build and Push Lorem Website
        # if: contains(github.event.head_commit.modified, 'lorem-website/') || github.event_name == 'workflow_dispatch'
        run: |
          cd lorem-website
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lorem-website:${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/lorem-website:${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }}

      - name: Build and Push Routing Service
        # if: contains(github.event.head_commit.modified, 'routing-service/') || github.event_name == 'workflow_dispatch'
        run: |
          cd routing-service
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/routing-service:${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/routing-service:${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }}