name: Docker Build, Scan, and Push

on:
  push:
    paths:
      - 'date-website/**'
      - 'lorem-website/**'
      - 'routing-service/**'
  workflow_dispatch:

jobs:
  build-scan-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Trivy
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb jammy main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update && sudo apt-get install -y trivy

      - name: Extract branch name and commit hash
        id: extract
        run: |
          BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          COMMIT_HASH=$(echo ${{ github.sha }} | cut -c1-6)
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV

      - name: Build, Scan, and Push Date Website
        run: |
          cd date-website
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/date-website:${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }}
          docker build -t $IMAGE_NAME .
          trivy image --exit-code 1 --severity HIGH,CRITICAL $IMAGE_NAME || exit 1
          docker push $IMAGE_NAME

      - name: Build, Scan, and Push Lorem Website
        run: |
          cd lorem-website
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/lorem-website:${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }}
          docker build -t $IMAGE_NAME .
          trivy image --exit-code 1 --severity HIGH,CRITICAL $IMAGE_NAME || exit 1
          docker push $IMAGE_NAME

      - name: Build, Scan, and Push Routing Service
        run: |
          cd routing-service
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/routing-service:${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }}
          docker build -t $IMAGE_NAME .
          trivy image --exit-code 1 --severity HIGH,CRITICAL $IMAGE_NAME || exit 1
          docker push $IMAGE_NAME
